theme = "ayu-evolve"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "position", "file-encoding", "file-type"]
